version: "3.9"

services:
  # NestJS Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: hiring-job-nestjs-docker
    ports:
      - 3333:3333
    env_file:
      - .env.api
    volumes:
      - ./api:/usr/src/app/api
    depends_on:
      - db
    environment:
      - PORT=3333
    networks:
      - meme-me

  # NextJS Service
  client:
    build:
      context: ./client
    container_name: hiring-job-nextjs-docker
    ports:
      - 3000:3000
    env_file:
      - .env.client
    depends_on:
      - api
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
      - /usr/src/app/client/.next